@Novacollege.WebApi_HostAddress = https://localhost:64014
@encodedCredentials = YWRtaW46YWRtaW4xMjM=

GET {{Novacollege.WebApi_HostAddress}}/provincias/summary
Accept: application/json
Authorization: Basic {{encodedCredentials}}