@Novacollege.WebApi_HostAddress = https://localhost:63187
@encodedCredentials = YWRtaW46YWRtaW4xMjM=

### get provincias/info
GET {{Novacollege.WebApi_HostAddress}}/provincias/info
Accept: application/json
Authorization: Basic {{encodedCredentials}}

### get estudiantes por provincia
GET {{Novacollege.WebApi_HostAddress}}/provincias/curso/1/estudiantes
Accept: application/json
Authorization: Basic {{encodedCredentials}}

### post /estudiantes
POST {{Novacollege.WebApi_HostAddress}}/estudiantes
Accept: application/json
Content-Type: application/json
Authorization: Basic {{encodedCredentials}}
{
    "apelEst": "Pérez",
    "nombEst": "Juan",
    "fnacEst": "1988-05-01",
    "sexoEst": "M",
    "direEst": "Av. Central 123",
    "tcolEst": "22334455",
    "ginsEst": "2024-01-10",
    "idDistrito": 1
}

### get /estudiantes?idProvincia
GET {{Novacollege.WebApi_HostAddress}}/estudiantes?idProvincia=1
Accept: application/json
Content-Type: application/json
Authorization: Basic {{encodedCredentials}}