// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Novacollege.Data.Data;

#nullable disable

namespace Novacollege.Data.Migrations
{
    [DbContext(typeof(NovacollegeDbContext))]
    [Migration("20260508101543_AddSPProvinciosPorEstudiantes")]
    partial class AddSPProvinciosPorEstudiantes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Novacollege.Data.Entities.Asignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechAsi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdDocente");

                    b.ToTable("TB_ASIGNACION", (string)null);
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostCur")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("DuraCur")
                        .HasColumnType("int");

                    b.Property<string>("NombCur")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TB_CURSO", (string)null);
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Distrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<string>("NombDis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdProvincia");

                    b.ToTable("TB_DISTRITO", (string)null);
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApelDoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DireDoc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GradDoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdProfesion")
                        .HasColumnType("int");

                    b.Property<string>("NcelDoc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NombDoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NtelDoc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("IdProfesion");

                    b.ToTable("TB_DOCENTE", (string)null);
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApelEst")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DireEst")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("FnacEst")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("GinsEst")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDistrito")
                        .HasColumnType("int");

                    b.Property<string>("NombEst")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SexoEst")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TcolEst")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("IdDistrito");

                    b.ToTable("TB_ESTUDIANTE", (string)null);
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FechMat")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("TB_MATRICULA", (string)null);
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Profesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombPro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TB_PROFESION", (string)null);
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombPro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TB_PROVINCIA", (string)null);
                });

            modelBuilder.Entity("Novacollege.Data.StoredProcedures.EstudiantesPorProvincia", b =>
                {
                    b.Property<int>("NumeroEstudiantes")
                        .HasColumnType("int");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("EstudiantesPorProvincia");
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Asignacion", b =>
                {
                    b.HasOne("Novacollege.Data.Entities.Curso", "Curso")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novacollege.Data.Entities.Docente", "Docente")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Distrito", b =>
                {
                    b.HasOne("Novacollege.Data.Entities.Provincia", "Provincia")
                        .WithMany("Distritos")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Docente", b =>
                {
                    b.HasOne("Novacollege.Data.Entities.Profesion", "Profesion")
                        .WithMany("Docentes")
                        .HasForeignKey("IdProfesion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesion");
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Estudiante", b =>
                {
                    b.HasOne("Novacollege.Data.Entities.Distrito", "Distrito")
                        .WithMany("Estudiantes")
                        .HasForeignKey("IdDistrito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Matricula", b =>
                {
                    b.HasOne("Novacollege.Data.Entities.Curso", "Curso")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novacollege.Data.Entities.Estudiante", "Estudiante")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Curso", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Distrito", b =>
                {
                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Docente", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Estudiante", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Profesion", b =>
                {
                    b.Navigation("Docentes");
                });

            modelBuilder.Entity("Novacollege.Data.Entities.Provincia", b =>
                {
                    b.Navigation("Distritos");
                });
#pragma warning restore 612, 618
        }
    }
}
